project_id = "pnqavlampfkuinxjspjg"

[functions.send-welcome-email]
verify_jwt = false

[functions.willow-chat]
verify_jwt = true

[functions.ensure-demo-user]
verify_jwt = false

[functions.moderate-letter]
verify_jwt = false

[functions.submit-letter-review]
verify_jwt = true
