// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pnqavlampfkuinxjspjg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBucWF2bGFtcGZrdWlueGpzcGpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1OTUyODIsImV4cCI6MjA3MDE3MTI4Mn0.PulhZc9vwqvPvPu5igw47Vg3m7Jz0Hfg5NEWbSkfUmw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});